import {
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

export const llmCalls = pgTable(
  'llm_calls',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    recordSchemaVersion: integer('record_schema_version').notNull(),
    callId: text('call_id').notNull(),
    attemptId: text('attempt_id').notNull(),
    callSiteId: text('call_site_id'),
    provider: text('provider').notNull(),
    model: text('model').notNull(),
    modelVersion: text('model_version'),
    responseId: text('response_id'),
    serviceTier: text('service_tier'),
    status: text('status').notNull(),
    finishReason: text('finish_reason'),
    latencyMs: integer('latency_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    cachedInputTokens: integer('cached_input_tokens'),
    thinkingTokens: integer('thinking_tokens'),
    totalTokens: integer('total_tokens'),
    costMicroUsd: integer('cost_micro_usd'),
    pricingVersion: text('pricing_version'),
    tokenDetails: jsonb('token_details').notNull(),
    rawUsage: jsonb('raw_usage').notNull(),
    providerMetadata: jsonb('provider_metadata'),
    warnings: jsonb('warnings'),
    generationConfig: jsonb('generation_config').notNull(),
    reasoningText: text('reasoning_text'),
    errorKind: text('error_kind'),
    errorMessage: text('error_message'),
    metadata: jsonb('metadata').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    attemptIdIdx: uniqueIndex('llm_calls_attempt_id_idx').on(table.attemptId),
  }),
)
