import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core'

export const llmCalls = pgTable(
  'llm_calls',
  {
    recordSchemaVersion: integer('record_schema_version').notNull(),
    callId: text('call_id').notNull(),
    attemptId: text('attempt_id').primaryKey(),
    callSiteId: text('call_site_id'),
    externalId: text('external_id'),
    authKeyId: text('auth_key_id'),
    provider: text('provider').notNull(),
    model: text('model').notNull(),
    modelVersion: text('model_version'),
    responseId: text('response_id'),
    serviceTier: text('service_tier'),
    servedServiceTier: text('served_service_tier'),
    status: text('status').notNull(),
    finishReason: text('finish_reason'),
    outputParsed: boolean('output_parsed'),
    latencyMs: integer('latency_ms'),
    queueDelayMs: integer('queue_delay_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    cachedInputTokens: integer('cached_input_tokens'),
    thinkingTokens: integer('thinking_tokens'),
    totalTokens: integer('total_tokens'),
    costMicroUsd: integer('cost_micro_usd'),
    pricingVersion: text('pricing_version'),
    tokenDetails: jsonb('token_details').notNull(),
    rawUsage: jsonb('raw_usage').notNull(),
    providerMetadata: jsonb('provider_metadata'),
    warnings: jsonb('warnings'),
    generationConfig: jsonb('generation_config').notNull(),
    reasoningText: text('reasoning_text'),
    errorKind: text('error_kind'),
    errorMessage: text('error_message'),
    attemptNumber: integer('attempt_number').notNull(),
    metadata: jsonb('metadata').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index('llm_calls_call_id_idx').on(table.callId),
    index('llm_calls_external_id_idx').on(table.externalId),
  ],
)
